// This file is auto-generated by @hey-api/openapi-ts

import { client, type Options } from '@hey-api/client-fetch';
import type {
    GetAccountsData,
    GetAccountsError,
    GetAccountsResponse,
    GetWorkspacesData,
    GetWorkspacesError,
    GetWorkspacesResponse,
    CreateWorkspaceData,
    CreateWorkspaceError,
    CreateWorkspaceResponse,
} from './types.gen';

/**
 * List Accounts
 */
export const getAccounts = (options?: Options<GetAccountsData>) => {
    return (options?.client ?? client).get<GetAccountsResponse, GetAccountsError>(
        {
            ...options,
            url: '/accounts',
        },
    );
};

/**
 * List Workspaces
 */
export const getWorkspaces = (options?: Options<GetWorkspacesData>) => {
    return (options?.client ?? client).get<
    GetWorkspacesResponse,
    GetWorkspacesError
  >({
      ...options,
      url: '/workspaces',
  });
};

/**
 * Create a Workspace
 * Workspaces represent a unit of infrastructure managed by terraform.
 *
 * To create a workspace you must pass `name` attribute and `environment` relationship.
 *
 * A workspace might be linked to a VCS repository, so that any git push will trigger a terraform Run
 * in the workspace.
 *
 */
export const createWorkspace = (options?: Options<CreateWorkspaceData>) => {
    return (options?.client ?? client).post<
    CreateWorkspaceResponse,
    CreateWorkspaceError
  >({
      ...options,
      url: '/workspaces',
  });
};
