// This file is auto-generated by @hey-api/openapi-ts

import { client, type Options } from '@hey-api/client-fetch';
import type { GetAccountsData, GetAccountsError, GetAccountsResponse } from './types.gen';

/**
 * List Accounts
 */
export const getAccounts = (options?: Options<GetAccountsData>) => {
    return (options?.client ?? client).get<GetAccountsResponse, GetAccountsError>({
        ...options,
        url: '/accounts'
    });
};
